### ISSUE TITLE
open position

### ISSUE THREAD

**Issue by Pandena** [amandin88/csgoroll-gw-picker#1]
Hello, are you still an active developer in cs? We would like to hire you to work on a p2p skin trading system for our platform

**Comment by amandin88** [comment]
Can you give me more details and a way to contact you directly? Maybe Discord?

**Comment by Pandena** [comment]
Please contact @Arya_Elsher on Telegram OR relaxing5057 (relaxing#5057) on discord for more details

**Comment by amandin88** [comment]
Please check discord, I sent a friend request.
